# Generated by Django 3.1.7 on 2021-02-25 08:07

from django.db import migrations, models
import login.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='WX_users',
            fields=[
                ('id', models.CharField(max_length=125, primary_key=True, serialize=False)),
                ('telephone', models.CharField(max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(error_messages={'email': '该邮箱已注册，请登录或尝试找回密码'}, max_length=254, unique=True)),
                ('telephone', models.CharField(default='11111111111', error_messages={'telephone': '该手机号已注册，请登录或尝试找回密码'}, max_length=11, unique=True)),
                ('password', models.CharField(max_length=250)),
                ('is_active', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', login.models.UserManager()),
            ],
        ),
    ]
