# Generated by Django 3.1.7 on 2021-02-25 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('types', models.CharField(default='offLine', max_length=10)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('status', models.CharField(default='', max_length=20)),
                ('rules', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Org_info',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=25)),
                ('introduction', models.TextField(max_length=200)),
                ('telephone', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Judger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=25)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.wx_users')),
            ],
        ),
        migrations.CreateModel(
            name='com_organizer',
            fields=[
                ('com_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='organizer.competition')),
                ('Organizer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizer.org_info')),
            ],
        ),
        migrations.CreateModel(
            name='com_judge',
            fields=[
                ('com_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='organizer.competition')),
                ('Judge_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizer.judger')),
            ],
        ),
    ]
